/** Route module loaders, shared by the router and by hover-prefetching in the sidebar. */
export const routeModules = {
  landing: () => import('@/pages/landing-page'),
  login: () => import('@/pages/login-page'),
  register: () => import('@/pages/register-page'),
  appShell: () => import('@/components/layout/app-shell'),
  dashboard: () => import('@/pages/dashboard-page'),
  graph: () => import('@/pages/graph-page'),
  runs: () => import('@/pages/runs-page'),
  runDetail: () => import('@/pages/run-detail-page'),
  agents: () => import('@/pages/agents-page'),
  issues: () => import('@/pages/issues-page'),
  inbox: () => import('@/pages/inbox-page'),
  memory: () => import('@/pages/memory-page'),
  projects: () => import('@/pages/projects-page'),
  project: () => import('@/pages/project-page'),
  members: () => import('@/pages/members-page'),
  teams: () => import('@/pages/teams-page'),
  usage: () => import('@/pages/usage-page'),
  audit: () => import('@/pages/audit-page'),
  settingsShell: () => import('@/components/layout/settings-shell'),
  settingsProfile: () => import('@/pages/settings/profile-page'),
  settingsPreferences: () => import('@/pages/settings/preferences-page'),
  settingsAi: () => import('@/pages/settings/ai-page'),
  settingsGuardrails: () => import('@/pages/settings/guardrails-page'),
  notFound: () => import('@/pages/not-found-page'),
};
