//! `nexc init`: writes a `.env` with freshly generated secrets.

use std::fmt::Write as _;
use std::path::Path;

use base64::Engine as _;

use crate::config::vars::ENV_VARS;
use crate::security::random::{random_bytes, random_token};

/// Renders the `.env` contents with new secrets.
pub fn render() -> String {
    let postgres_password = hex::encode(random_bytes::<24>());
    let generated = |name: &str| -> Option<String> {
        Some(match name {
            "NEXC_JWT_SECRET" | "NEXC_RUNTIME_TOKEN" => random_token(),
            "NEXC_MASTER_KEY" => {
                base64::engine::general_purpose::STANDARD.encode(random_bytes::<32>())
            }
            "POSTGRES_PASSWORD" => postgres_password.clone(),
            "NEXC_DATABASE_URL" => {
                format!("postgres://nexc:{postgres_password}@localhost:5432/nexc")
            }
            _ => return None,
        })
    };
    let mut out = String::from(
        "# nexc-engine configuration, generated by `nexc init`.\n\
         # Keep this file private (it holds secrets). Inside docker compose the\n\
         # database host is the service name instead of localhost.\n\n",
    );
    for var in ENV_VARS {
        let _ = writeln!(out, "# {}", var.help);
        match generated(var.name) {
            Some(value) => {
                let _ = writeln!(out, "{}={value}\n", var.name);
            }
            None if var.default.is_empty() => {
                let _ = writeln!(out, "# {}=\n", var.name);
            }
            None => {
                let _ = writeln!(out, "{}={}\n", var.name, var.default);
            }
        }
    }
    out
}

/// Writes the file (mode 0600 on Unix); refuses to overwrite without `force`.
pub fn run(path: &Path, force: bool) -> anyhow::Result<()> {
    anyhow::ensure!(
        force || !path.exists(),
        "{} exists; use --force to overwrite",
        path.display()
    );
    let dir = path
        .parent()
        .filter(|d| !d.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    std::fs::create_dir_all(dir)?;
    let tmp = dir.join(format!(".env.{}.tmp", std::process::id()));
    std::fs::write(&tmp, render())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o600))?;
    }
    std::fs::rename(&tmp, path)?;
    println!("wrote {} with new secrets", path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Settings;

    #[test]
    fn generated_env_is_valid_configuration() {
        let text = render();
        let map: std::collections::HashMap<String, String> = text
            .lines()
            .filter(|l| !l.starts_with('#') && l.contains('='))
            .filter_map(|l| l.split_once('=').map(|(k, v)| (k.to_owned(), v.to_owned())))
            .collect();
        let settings = Settings::from_lookup(|k| map.get(k).cloned()).unwrap();
        assert_eq!(settings.jwt_secret.expose().len(), 43);
        assert!(
            settings
                .database_url
                .expose()
                .contains(&map["POSTGRES_PASSWORD"])
        );
        assert_ne!(render(), text, "secrets are fresh every time");
    }
}
