/**
 * Type-only drift check between the hand-written zod schemas (the runtime guard and the source of
 * our TS types) and the OpenAPI types generated by `pnpm gen:api`.
 *
 * Each entry asserts that the generated schema of that name is assignable to our zod-inferred type.
 * While `schema.d.ts` is the empty placeholder every check resolves to `true`; once real types are
 * generated, a mismatch makes `pnpm typecheck` fail on the offending line.
 */
import type { Agent } from '@/schemas/agent';
import type { AuthResponse, User } from '@/schemas/auth';
import type {
  EdgeSuggestion,
  Graph,
  GraphAnalysis,
  GraphEdge,
  GraphNode,
  GraphSummary,
} from '@/schemas/graph';
import type { Memory } from '@/schemas/memory';
import type { OrchestratorStatus } from '@/schemas/orchestrator';
import type { Plan } from '@/schemas/plan';
import type { Artifact, NodeRun, Run } from '@/schemas/run';
import type { LlmSettings } from '@/schemas/settings';
import type { GraphTemplate } from '@/schemas/template';

import type { components } from './schema';

type Generated = components['schemas'];

type Matches<Name extends string, Ours> = Name extends keyof Generated
  ? Generated[Name] extends Ours
    ? true
    : { drift: Name; generated: Generated[Name]; expected: Ours }
  : true;

type Assert<T extends true> = T;

export type ContractDrift = [
  Assert<Matches<'User', User>>,
  Assert<Matches<'AuthResponse', AuthResponse>>,
  Assert<Matches<'LlmSettings', LlmSettings>>,
  Assert<Matches<'GraphNode', GraphNode>>,
  Assert<Matches<'GraphEdge', GraphEdge>>,
  Assert<Matches<'GraphSummary', GraphSummary>>,
  Assert<Matches<'Graph', Graph>>,
  Assert<Matches<'EdgeSuggestion', EdgeSuggestion>>,
  Assert<Matches<'GraphAnalysis', GraphAnalysis>>,
  Assert<Matches<'GraphTemplate', GraphTemplate>>,
  Assert<Matches<'Plan', Plan>>,
  Assert<Matches<'NodeRun', NodeRun>>,
  Assert<Matches<'Run', Run>>,
  Assert<Matches<'Artifact', Artifact>>,
  Assert<Matches<'Agent', Agent>>,
  Assert<Matches<'Memory', Memory>>,
  Assert<Matches<'OrchestratorStatus', OrchestratorStatus>>,
];
