/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's agents. */
        get: operations["list"];
        put?: never;
        /** Adds an agent. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes an agent (its reports no longer report to anyone). */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Updates an agent. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/artifacts/{aid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Downloads one artifact as an attachment. */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifies credentials and starts a session. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the session: revokes the refresh-token family and clears the cookie. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotates the refresh token (cookie + `X-Requested-With: nexc`). */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an account (when signups are enabled) and starts a session. */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's graphs, most recently updated first. */
        get: operations["list"];
        put?: never;
        /** Creates an empty graph. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/from-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new graph from a template. */
        post: operations["instantiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A graph with nodes and edges. Supports `If-None-Match` (304). */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Deletes a graph with everything in it. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Updates name, description or goal. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/graphs/{gid}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topological order, parallel levels, critical path, cycles and components. */
        get: operations["analysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds an edge; a `depends_on` edge that would create a cycle is a 409. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/edges/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes an edge. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events of a graph (contract §6). */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a node. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/nodes/{nid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes a node and its edges. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Updates a node. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/graphs/{gid}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts planning; progress streams over SSE (`plan.*` events). */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/plans/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A plan of a graph. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/plans/{pid}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applies a ready plan to the graph. */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs of a graph, newest first (at most 100). */
        get: operations["list"];
        put?: never;
        /** Queues a run; progress streams over SSE (`run.*`, `node.*` events). */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency suggestions (similarity + BM25, near-duplicates skipped). */
        get: operations["suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graphs/{gid}/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Collaborative WebSocket of a graph (contract §7). The `Origin` header,
         *     when present, must be one of `NEXC_CORS_ORIGINS`.
         */
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process serves HTTP. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists (newest first) or searches the caller's memories. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forgets a memory. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orchestrator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue, running work, agents and backend health for the caller. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the database answers. */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issues a single-use ticket for one of the caller's graphs. */
        post: operations["ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run with its node results. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{rid}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts of a run. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{rid}/artifacts.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All artifacts of a run as a zip (`<node_id>/<path>` entries). */
        get: operations["zip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{rid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancels a queued or running run. */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The effective LLM settings of the caller. */
        get: operations["get_llm"];
        /** Updates provider, model, base URL and (encrypted) API key. */
        put: operations["put_llm"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The built-in templates. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics; requires `NEXC_METRICS_TOKEN` or an admin access token. */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An agent in the user's organisation. */
        Agent: {
            /** Format: int64 */
            budget_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            heartbeat_at: string | null;
            /** Format: uuid */
            id: string;
            model: string;
            name: string;
            /** Format: uuid */
            reports_to: string | null;
            role: string;
            runtime: components["schemas"]["AgentRuntime"];
            /** Format: int64 */
            spent_tokens: number;
            status: components["schemas"]["AgentStatus"];
            system_prompt: string;
            title: string;
        };
        /**
         * @description Where an agent runs: the Python agent runtime or the built-in LLM executor.
         * @enum {string}
         */
        AgentRuntime: "python" | "builtin";
        /**
         * @description Whether an agent accepts work.
         * @enum {string}
         */
        AgentStatus: "active" | "paused" | "over_budget";
        /** @description A file produced by a node during a run. */
        Artifact: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            mime: string;
            /** Format: uuid */
            node_id: string;
            /** @description Relative path inside the run (also the download file name). */
            path: string;
            /** Format: uuid */
            run_id: string;
            /** Format: int64 */
            size: number;
        };
        /**
         * @description Returned by register / login / refresh. The refresh token travels only in
         *     the `nexc_refresh` HttpOnly cookie.
         */
        AuthResponse: {
            access_token: string;
            /**
             * Format: int64
             * @description Access token lifetime in seconds.
             */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        /** @description Health of one backend the engine depends on. */
        BackendHealth: {
            detail: string | null;
            enabled: boolean;
            ok: boolean;
            url: string | null;
        };
        /** @description Health of all backends. */
        Backends: {
            agent_runtime: components["schemas"]["BackendHealth"];
            llm: components["schemas"]["BackendHealth"];
            symphony: components["schemas"]["BackendHealth"];
        };
        /** @description `POST /agents` body. */
        CreateAgent: {
            /** Format: int64 */
            budget_tokens?: number | null;
            model?: string | null;
            name: string;
            /** Format: uuid */
            reports_to?: string | null;
            role: string;
            runtime?: components["schemas"]["AgentRuntime"] | null;
            system_prompt?: string;
            title?: string;
        };
        /** @description `POST /graphs/{gid}/edges` body. `depends_on`: source finishes before target. */
        CreateEdge: {
            kind?: components["schemas"]["EdgeKind"] | null;
            /** Format: uuid */
            source: string;
            /** Format: uuid */
            target: string;
        };
        /** @description `POST /graphs` body. */
        CreateGraph: {
            description?: string;
            goal?: string;
            name: string;
        };
        /** @description `POST /graphs/{gid}/nodes` body. */
        CreateNode: {
            agent_role?: string | null;
            content?: string;
            executor?: components["schemas"]["Executor"] | null;
            kind?: components["schemas"]["NodeKind"] | null;
            tags?: string[];
            title: string;
            /** Format: double */
            x?: number | null;
            /** Format: double */
            y?: number | null;
        };
        /** @description `POST /graphs/{gid}/plan` body. */
        CreatePlan: {
            instructions?: string;
        };
        /** @description `POST /graphs/{gid}/runs` body. */
        CreateRun: {
            /** @description Ignore the result cache. */
            force?: boolean;
            /**
             * Format: int32
             * @description Parallel nodes, 1–32 (default `NEXC_MAX_CONCURRENCY`).
             */
            max_concurrency?: number | null;
            /** @description Run only these nodes (default: all). */
            node_ids?: string[] | null;
        };
        /** @description A cursor position on the canvas. */
        Cursor: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /**
         * @description Semantics of an edge. `depends_on`: source must finish before target runs.
         * @enum {string}
         */
        EdgeKind: "depends_on" | "relates_to";
        /**
         * @description Who created an edge (`auto` = `[[wikilink]]` dependency detection).
         * @enum {string}
         */
        EdgeOrigin: "user" | "auto" | "plan";
        /** @description A suggested dependency produced by dependency detection. */
        EdgeSuggestion: {
            /** @description Human readable explanation. */
            reason: string;
            /**
             * Format: double
             * @description Confidence in `[0, 1]`.
             */
            score: number;
            /** Format: uuid */
            source: string;
            /** Format: uuid */
            target: string;
        };
        /**
         * @description Which executor runs a node.
         * @enum {string}
         */
        Executor: "llm" | "agent" | "symphony";
        /** @description `POST /graphs/from-template` body. */
        FromTemplate: {
            /** @description Graph name (default: the template's name, plus the topic when given). */
            name?: string | null;
            template_id: string;
            /**
             * @description What this instance is about, e.g. the research question or product. It is put at the top
             *     of the graph goal so every planner and node prompt sees it.
             */
            topic?: string | null;
        };
        /** @description A full graph with its nodes and edges. */
        Graph: {
            /** Format: date-time */
            created_at: string;
            description: string;
            edges: components["schemas"]["GraphEdge"][];
            goal: string;
            /** Format: uuid */
            id: string;
            name: string;
            nodes: components["schemas"]["GraphNode"][];
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Incremented on every mutation of the graph, its nodes or edges.
             */
            version: number;
        };
        /** @description Structural analysis of the `depends_on` graph. */
        GraphAnalysis: {
            /** @description Weakly connected components over all edges. */
            components: string[][];
            /** @description The longest dependency chain. */
            critical_path: string[];
            /** @description Strongly connected components with more than one node (should be empty). */
            cycles: string[][];
            /** @description Parallel execution waves (every node in a wave only depends on earlier waves). */
            levels: string[][];
            /** @description A topological order of the acyclic part of the graph. */
            topo_order: string[];
        };
        /** @description A directed edge between two nodes of the same graph. */
        GraphEdge: {
            /** Format: uuid */
            graph_id: string;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["EdgeKind"];
            origin: components["schemas"]["EdgeOrigin"];
            /** Format: uuid */
            source: string;
            /** Format: uuid */
            target: string;
            /** Format: double */
            weight: number;
        };
        /** @description A note / task on the canvas. */
        GraphNode: {
            agent_role: string | null;
            content: string;
            /** Format: date-time */
            created_at: string;
            executor: components["schemas"]["Executor"];
            /** Format: uuid */
            graph_id: string;
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["NodeKind"];
            origin: components["schemas"]["NodeOrigin"];
            output: string | null;
            status: components["schemas"]["NodeStatus"];
            tags: string[];
            title: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @description Row of the graph list. */
        GraphSummary: {
            description: string;
            /** Format: int64 */
            edge_count: number;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int64 */
            node_count: number;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A template as listed by `GET /templates`. */
        GraphTemplate: {
            category: string;
            description: string;
            id: string;
            name: string;
            /** Format: int64 */
            node_count: number;
            tags: string[];
        };
        /** @description Health probe response. */
        Health: {
            status: string;
            version: string;
        };
        /**
         * @description Where the effective API key comes from.
         * @enum {string}
         */
        KeySource: "user" | "server" | "none";
        /**
         * @description LLM backend family. `demo` is a deterministic offline provider; `claude_code` runs the
         *     local Claude Code CLI with the operator's own login (no API key).
         * @enum {string}
         */
        LlmProviderKind: "anthropic" | "openai_compatible" | "demo" | "claude_code";
        /** @description LLM configuration as seen by the user (the key itself is never returned). */
        LlmSettings: {
            base_url: string | null;
            has_api_key: boolean;
            /** @description Last four characters of the key, prefixed with `…`. */
            key_hint: string | null;
            model: string;
            provider: components["schemas"]["LlmProviderKind"];
            source: components["schemas"]["KeySource"];
        };
        /**
         * @description Severity of a `node.log` line.
         * @enum {string}
         */
        LogLevel: "debug" | "info" | "warn" | "error";
        /** @description `POST /auth/login` body. */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description A stored memory. `score` is set only for search results. */
        Memory: {
            /** Format: int64 */
            access_count: number;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            graph_id: string | null;
            /** Format: uuid */
            id: string;
            /**
             * Format: double
             * @description Importance in `[0, 1]`.
             */
            importance: number;
            kind: components["schemas"]["MemoryKind"];
            /** Format: uuid */
            node_id: string | null;
            scope: components["schemas"]["MemoryScope"];
            /** Format: double */
            score: number | null;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description What a memory captures.
         * @enum {string}
         */
        MemoryKind: "fact" | "experience" | "observation" | "preference";
        /**
         * @description Visibility scope of a memory.
         * @enum {string}
         */
        MemoryScope: "user" | "graph" | "node";
        /**
         * @description What a node represents.
         * @enum {string}
         */
        NodeKind: "topic" | "task" | "research" | "code" | "document" | "output";
        /**
         * @description Who created a node.
         * @enum {string}
         */
        NodeOrigin: "user" | "plan";
        /** @description Result of one node within a run. */
        NodeRun: {
            /** Format: int32 */
            attempt: number;
            cached: boolean;
            error: string | null;
            executor: components["schemas"]["Executor"];
            /** Format: date-time */
            finished_at: string | null;
            /** Format: uuid */
            node_id: string;
            output_preview: string | null;
            /** Format: date-time */
            started_at: string | null;
            status: components["schemas"]["NodeStatus"];
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
        };
        /**
         * @description Execution status of a node (last run).
         * @enum {string}
         */
        NodeStatus: "idle" | "queued" | "running" | "succeeded" | "failed" | "skipped" | "cancelled";
        /** @description `node.status` payload. */
        NodeStatusEvent: {
            /** Format: int32 */
            attempt: number;
            cached: boolean;
            error?: string | null;
            /** Format: uuid */
            node_id: string;
            /** Format: uuid */
            run_id: string;
            status: components["schemas"]["NodeStatus"];
        };
        /** @description Live view of the orchestrator for the current user. */
        OrchestratorStatus: {
            /** Format: int64 */
            active_runs: number;
            /** Format: int64 */
            agents_active: number;
            backends: components["schemas"]["Backends"];
            /** @description True when the effective LLM provider is the offline demo provider. */
            demo_mode: boolean;
            /** Format: int64 */
            queue_depth: number;
            /** Format: int64 */
            running_nodes: number;
        };
        /** @description A plan as returned by the API. */
        Plan: {
            /** Format: date-time */
            created_at: string;
            edges: components["schemas"]["ProposedEdge"][];
            error: string | null;
            /** Format: uuid */
            graph_id: string;
            /** Format: uuid */
            id: string;
            nodes: components["schemas"]["ProposedNode"][];
            status: components["schemas"]["PlanStatus"];
            summary: string;
        };
        /**
         * @description Lifecycle of a plan.
         * @enum {string}
         */
        PlanStatus: "streaming" | "ready" | "failed" | "applied";
        /** @description An RFC 7807 problem document. */
        Problem: {
            detail?: string | null;
            /** @description Field validation messages (422 only). */
            errors?: {
                [key: string]: string[];
            } | null;
            /** Format: int32 */
            status: number;
            title: string;
            /** @description Always `about:blank`. */
            type: string;
        };
        /** @description A `depends_on` edge between two proposed nodes (by `ref`). */
        ProposedEdge: {
            source_ref: string;
            target_ref: string;
        };
        /** @description A node in a plan proposal. `ref` is a plan-local identifier used by edges. */
        ProposedNode: {
            agent_role: string;
            content: string;
            executor: components["schemas"]["Executor"];
            /**
             * Format: uuid
             * @description Id of the existing node this refines, or `null` for a new node.
             *     Malformed ids from the model are read as `null`.
             */
            existing_id: string | null;
            kind: components["schemas"]["NodeKind"];
            ref: string;
            tags: string[];
            title: string;
        };
        /** @description `POST /auth/register` body. */
        RegisterRequest: {
            email: string;
            name: string;
            /** @description 12–128 characters. */
            password: string;
        };
        /**
         * @description Authorization role of a user.
         * @enum {string}
         */
        Role: "admin" | "user";
        /** @description One execution of (part of) a graph. */
        Run: {
            /** Format: double */
            cost_usd: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at: string | null;
            /** Format: uuid */
            graph_id: string;
            /** Format: uuid */
            id: string;
            node_runs: components["schemas"]["NodeRun"][];
            /** Format: date-time */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
        };
        /**
         * @description Lifecycle of a run.
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @description One server-sent event (`data:` payload). The variant determines the SSE `event:` name. */
        SseEvent: {
            /** Format: uuid */
            plan_id: string;
        } | {
            node: components["schemas"]["ProposedNode"];
            /** Format: uuid */
            plan_id: string;
        } | {
            edge: components["schemas"]["ProposedEdge"];
            /** Format: uuid */
            plan_id: string;
        } | {
            plan: components["schemas"]["Plan"];
        } | {
            error: string;
            /** Format: uuid */
            plan_id: string;
        } | {
            run: components["schemas"]["Run"];
        } | components["schemas"]["NodeStatusEvent"] | {
            delta: string;
            /** Format: uuid */
            node_id: string;
            /** Format: uuid */
            run_id: string;
        } | {
            level: components["schemas"]["LogLevel"];
            message: string;
            /** Format: uuid */
            node_id: string;
            /** Format: uuid */
            run_id: string;
        } | {
            /** Format: uuid */
            node_id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
        } | {
            artifact: components["schemas"]["Artifact"];
        } | {
            run: components["schemas"]["Run"];
        };
        /** @description `POST /realtime/tickets` body. */
        TicketRequest: {
            /** Format: uuid */
            graph_id: string;
        };
        /** @description A single-use realtime ticket. */
        TicketResponse: {
            /**
             * Format: int64
             * @description Seconds until the ticket expires.
             */
            expires_in: number;
            ticket: string;
        };
        /** @description `PATCH /agents/{id}` body (any subset; `reports_to: null` detaches). */
        UpdateAgent: {
            /** Format: int64 */
            budget_tokens?: number | null;
            model?: string | null;
            name?: string | null;
            /** Format: uuid */
            reports_to?: string | null;
            role?: string | null;
            runtime?: components["schemas"]["AgentRuntime"] | null;
            status?: components["schemas"]["AgentStatus"] | null;
            system_prompt?: string | null;
            title?: string | null;
        };
        /** @description `PATCH /graphs/{gid}` body. */
        UpdateGraph: {
            description?: string | null;
            goal?: string | null;
            name?: string | null;
        };
        /**
         * @description `PUT /settings/llm` body. `api_key`: omitted keeps the stored key,
         *     `""` deletes it, any other value replaces it.
         */
        UpdateLlmSettings: {
            api_key?: string | null;
            base_url?: string | null;
            model: string;
            provider: components["schemas"]["LlmProviderKind"];
        };
        /**
         * @description `PATCH /graphs/{gid}/nodes/{nid}` body: any subset of the mutable node
         *     fields. `agent_role` and `output` accept `null` to clear them.
         */
        UpdateNode: {
            agent_role?: string | null;
            content?: string | null;
            executor?: components["schemas"]["Executor"] | null;
            kind?: components["schemas"]["NodeKind"] | null;
            output?: string | null;
            status?: components["schemas"]["NodeStatus"] | null;
            tags?: string[] | null;
            title?: string | null;
            /** Format: double */
            x?: number | null;
            /** Format: double */
            y?: number | null;
        };
        /** @description A registered user (never includes credentials). */
        User: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        /** @description A server → client WebSocket message. */
        WsMessage: {
            node: components["schemas"]["GraphNode"];
            /** @enum {string} */
            type: "node.upserted";
        } | {
            /** Format: uuid */
            node_id: string;
            /** @enum {string} */
            type: "node.deleted";
        } | {
            edge: components["schemas"]["GraphEdge"];
            /** @enum {string} */
            type: "edge.upserted";
        } | {
            /** Format: uuid */
            edge_id: string;
            /** @enum {string} */
            type: "edge.deleted";
        } | {
            graph: components["schemas"]["GraphSummary"];
            /** @enum {string} */
            type: "graph.updated";
        } | {
            items: components["schemas"]["EdgeSuggestion"][];
            /** @enum {string} */
            type: "suggestions";
        } | {
            cursor?: components["schemas"]["Cursor"] | null;
            name: string;
            /** @enum {string} */
            type: "presence";
            /** Format: uuid */
            user_id: string;
        } | {
            /** @enum {string} */
            type: "pong";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgent"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artifact id */
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": number[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; refresh cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Too many failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Must be `nexc` (CSRF guard) */
                "X-Requested-With": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing CSRF header */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Must be `nexc` (CSRF guard) */
                "X-Requested-With": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token; rotated cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Missing, expired, revoked or reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing CSRF header */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered; refresh cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Signups disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description E-mail already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSummary"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGraph"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    instantiate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromTemplate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Unknown template */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Strong entity tag */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGraph"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    analysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphAnalysis"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdge"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphEdge"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Would create a cycle, or already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
                /** @description Edge id */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    events: {
        parameters: {
            query: {
                /** @description Ticket from `POST /realtime/tickets`. */
                ticket: string;
            };
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNode"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
                /** @description Node id */
                nid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
                /** @description Node id */
                nid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlan"];
            };
        };
        responses: {
            /** @description Plan is streaming */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description No LLM API key configured */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
                /** @description Plan id */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
                /** @description Plan id */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Plan is not ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRun"];
            };
        };
        responses: {
            /** @description Run queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid selection or no LLM API key configured */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    suggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeSuggestion"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    websocket: {
        parameters: {
            query: {
                /** @description Ticket from `POST /realtime/tickets`. */
                ticket: string;
            };
            header?: never;
            path: {
                /** @description Graph id */
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Origin not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Restrict to a graph (plus user-scope memories). */
                graph_id?: string | null;
                /** @description Hybrid search query; results then carry a `score`. */
                q?: string | null;
                /** @description 1–100, default 20. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestratorStatus"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run id */
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run id */
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    zip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run id */
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": number[];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Archive too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run id */
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_llm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmSettings"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_llm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLlmSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmSettings"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphTemplate"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
