//! Catalogue of the environment variables the backend reads. Used by
//! `nexc config show` (with redaction) and `nexc init` (the `.env` template).

/// One documented environment variable.
#[derive(Debug, Clone, Copy)]
pub struct EnvVar {
    pub name: &'static str,
    /// Default shown in docs / written by `nexc init` (`""` = unset).
    pub default: &'static str,
    /// Whether the value must be redacted when displayed.
    pub secret: bool,
    pub help: &'static str,
}

const fn var(
    name: &'static str,
    default: &'static str,
    secret: bool,
    help: &'static str,
) -> EnvVar {
    EnvVar {
        name,
        default,
        secret,
        help,
    }
}

/// Every variable, grouped as in `.env.example`.
pub const ENV_VARS: &[EnvVar] = &[
    var("NEXC_ENV", "development", false, "development | production"),
    var("NEXC_HOST", "0.0.0.0", false, "bind address"),
    var("NEXC_PORT", "8080", false, "bind port"),
    var("POSTGRES_USER", "nexc", false, "postgres container user"),
    var(
        "POSTGRES_PASSWORD",
        "",
        true,
        "postgres container password (generated by `nexc init`)",
    ),
    var("POSTGRES_DB", "nexc", false, "postgres database name"),
    var(
        "NEXC_DATABASE_URL",
        "",
        true,
        "postgres://user:password@host:5432/db (PostgreSQL 17)",
    ),
    var("NEXC_DB_MAX_CONNECTIONS", "20", false, "database pool size"),
    var(
        "NEXC_DATA_DIR",
        "./data",
        false,
        "artifacts and managed files",
    ),
    var(
        "NEXC_JWT_SECRET",
        "",
        true,
        "HS256 signing secret, at least 32 bytes",
    ),
    var(
        "NEXC_MASTER_KEY",
        "",
        true,
        "base64 of 32 random bytes; encrypts stored API keys",
    ),
    var(
        "NEXC_CORS_ORIGINS",
        "http://localhost:5173",
        false,
        "comma separated allowed origins",
    ),
    var(
        "NEXC_COOKIE_SECURE",
        "",
        false,
        "Secure refresh cookie (always on in production)",
    ),
    var(
        "NEXC_ALLOW_SIGNUP",
        "true",
        false,
        "allow self registration",
    ),
    var(
        "NEXC_ADMIN_EMAIL",
        "",
        false,
        "bootstrap admin e-mail (with NEXC_ADMIN_PASSWORD)",
    ),
    var("NEXC_ADMIN_PASSWORD", "", true, "bootstrap admin password"),
    var(
        "NEXC_ACCESS_TTL_SECS",
        "900",
        false,
        "access token lifetime",
    ),
    var(
        "NEXC_REFRESH_TTL_SECS",
        "1209600",
        false,
        "refresh token lifetime",
    ),
    var(
        "NEXC_LLM_PROVIDER",
        "anthropic",
        false,
        "anthropic | openai_compatible | demo",
    ),
    var("NEXC_LLM_MODEL", "claude-opus-5", false, "default model"),
    var("NEXC_LLM_BASE_URL", "", false, "provider base URL override"),
    var(
        "NEXC_LLM_FALLBACKS",
        "true",
        false,
        "Anthropic server-side refusal fallbacks",
    ),
    var(
        "ANTHROPIC_API_KEY",
        "",
        true,
        "server-wide default Anthropic key",
    ),
    var(
        "NEXC_RUNTIME_URL",
        "http://localhost:8090",
        false,
        "Python agent runtime",
    ),
    var(
        "NEXC_RUNTIME_TOKEN",
        "",
        true,
        "shared bearer secret, at least 32 characters",
    ),
    var(
        "NEXC_SYMPHONY_ENABLED",
        "false",
        false,
        "enable the texc-symphony executor",
    ),
    var(
        "NEXC_SYMPHONY_URL",
        "http://localhost:4000",
        false,
        "texc-symphony HTTP API",
    ),
    var(
        "NEXC_SYMPHONY_WORKFLOW",
        "./data/symphony/WORKFLOW.md",
        false,
        "managed workflow file",
    ),
    var(
        "NEXC_SYMPHONY_AGENT_COMMAND",
        "",
        false,
        "agent command for texc-symphony (default: Symphony's own, Codex)",
    ),
    var(
        "NEXC_MAX_CONCURRENCY",
        "4",
        false,
        "default parallel nodes per run",
    ),
    var(
        "NEXC_MAX_ATTEMPTS",
        "3",
        false,
        "attempts per node for retryable errors",
    ),
    var(
        "NEXC_NODE_TIMEOUT_SECS",
        "600",
        false,
        "per-attempt node timeout",
    ),
    var(
        "NEXC_TRUST_PROXY",
        "false",
        false,
        "trust X-Forwarded-For from a reverse proxy",
    ),
    var(
        "NEXC_METRICS_TOKEN",
        "",
        true,
        "bearer token for GET /metrics",
    ),
    var(
        "NEXC_LOG",
        "info",
        false,
        "tracing filter (RUST_LOG syntax)",
    ),
];
